server:
  port: 8085

spring:
  application:
    name: clinic-api
  datasource:
    url: jdbc:postgresql://localhost:5432/clinic
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true